  CREATE TABLE ALERTS
   (    EVENT_DATE DATE,
        EVENT_TYPE VARCHAR2(16) NOT NULL ENABLE,
        RESULT NUMBER,
        RESULT_TEXT VARCHAR2(4000),
        INSTANCE_NAME VARCHAR2(16),
         CONSTRAINT EVENT_TYPE_IN CHECK (event_type in ('ALERT FILE',
           'BACKUPS','STORAGE','ARCHIVE','GROWTH','SESSIONS',
           'RESOURCE LIMIT')) ENABLE
   ) 
/